### PR TITLE
IterateForAssignment: Properly handle invalid syntax for exclude range

### LINKED ISSUE #364: [BUG] exclude range currently does not correctly handle invalid syntax
**Describe the bug**
Invalid syntax in an exclude range is currently ignored, and a nil pointer is added to excludeRanges, leading to a nil pointer exception in skipExludedSubnets
This also includes cases where the excludeRange is a single IP address

**Expected behavior**

**To Reproduce**
1.  See the unit tests for the submitted patch
2. 
3.

**Environment**:
- Whereabouts version : N/A
- Kubernetes version (use `kubectl version`): N/A
- Network-attachment-definition: N/A
- Whereabouts configuration (on the host): N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Others: N/A

**Additional info / context**
Add any other information / context about the problem here.

### PR DESCRIPTION
**Pull request by andreaskaris**
Correctly handle errors from parsing exclude ranges to avoid issues with nil pointer exceptions.
Parse single IP addresses such as 192.168.123.10 or fe02::10 by and convert them to CIDRs by appending the correct 
prefix.

Fixes #364 

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer** *(optional)*:

### CODE REVIEW

File: pkg/allocate/allocate.go [hunk 1]
```diff
@@ -144,3 +148,28 @@ func skipExcludedSubnets(ip net.IP, excluded []*net.IPNet) net.IP {
...
+	// we got earlier.
+	ip := net.ParseIP(s)
+	if ip == nil {
+		return nil, err
+	}
+	// If the address parses, check if it's IPv4 or IPv6 and add the correct prefix.
+	if ip.To4() != nil {
+		_, subnet, err = net.ParseCIDR(fmt.Sprintf("%s/32", s))
+	} else {
+		_, subnet, err = net.ParseCIDR(fmt.Sprintf("%s/128", s))
```
Comment (dougbtv) [inline pkg/allocate/allocate.go:172]: Yep, I'm into this approach of adding the suffix if it's a single IP, nice call

**Review by dougbtv — APPROVED** [review]
